/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Pretendard-Regular"],
        "pretendard-regular": ["Pretendard-Regular"],
        "pretendard-medium": ["Pretendard-Medium"],
        "pretendard-semibold": ["Pretendard-SemiBold"],
        "pretendard-bold": ["Pretendard-Bold"],
      },
      fontSize: {
        xs: ["11px", "15px"],
        sm: ["13px", "18px"],
        base: ["15px", "21px"],
        md: ["17px", "24px"],
        lg: ["19px", "27px"],
        xl: ["22px", "30px"],
        "2xl": ["28px", "34px"],
        "3xl": ["36px", "40px"],
      },
      colors: {
        primary: "#1D9E75",
        "primary-foreground": "#ffffff",
        background: "#ffffff",
        foreground: "#1a1a1a",
        card: "#ffffff",
        "card-foreground": "#1a1a1a",
        border: "#e2e8f0",
        muted: "#f1f5f9",
        "muted-foreground": "#64748b",
        body: "#555555",
        subtle: "#999999",
        disabled: "#bbbbbb",
        hairline: "#dddddd",
        divider: "#e5e5e0",
        "background-muted": "#f5f5f0",
        "surface-muted": "#f9f9f6",
        chip: "#f0f0eb",
        danger: "#E24B4A",
        warning: "#EF9F27",
        ring: "#1D9E75",
      },
    },
  },
  plugins: [],
};
