export const fontFamily = {
  regular: "Pretendard-Regular",
  medium: "Pretendard-Medium",
  semibold: "Pretendard-SemiBold",
  bold: "Pretendard-Bold",
} as const;

export const fontSize = {
  xs: 11,
  sm: 13,
  base: 15,
  md: 17,
  lg: 19,
  xl: 22,
  "2xl": 28,
  "3xl": 36,
} as const;

export const lineHeight = {
  xs: 15,
  sm: 18,
  base: 21,
  md: 24,
  lg: 27,
  xl: 30,
  "2xl": 34,
  "3xl": 40,
} as const;

export const palette = {
  green700: "#0F6E56",
  green600: "#1D9E75",
  green200: "#9FE1CB",
  green50: "#E1F5EE",
  red500: "#E24B4A",
  amber500: "#EF9F27",
  ink900: "#1a1a1a",
  ink700: "#555555",
  ink500: "#888888",
  ink400: "#999999",
  ink300: "#bbbbbb",
  ink200: "#cccccc",
  ink150: "#dddddd",
  stone100: "#f5f5f0",
  stone80: "#f8f8f4",
  stone70: "#f9f9f6",
  stone60: "#f0f0eb",
  stone40: "#eeeeee",
  stone30: "#e5e5e0",
  slate100: "#f1f5f9",
  slate300: "#cbd5e1",
  slate400: "#94a3b8",
  slate500: "#64748b",
  slate200: "#e2e8f0",
  white: "#ffffff",
  black: "#000000",
  googleBlue: "#4285F4",
} as const;

export const semanticColors = {
  light: {
    accent: palette.green600,
    accentStrong: palette.green700,
    accentSubtle: palette.green50,
    accentBorder: palette.green200,
    textPrimary: palette.ink900,
    textSecondary: palette.ink700,
    textTertiary: palette.ink500,
    textMuted: palette.ink400,
    textDisabled: palette.ink300,
    iconMuted: palette.ink200,
    page: palette.white,
    pageMuted: palette.stone100,
    surface: palette.white,
    surfacePressed: palette.stone60,
    surfaceMuted: palette.stone70,
    surfaceRaised: palette.white,
    chip: palette.stone60,
    border: palette.slate200,
    borderMuted: palette.ink150,
    borderSubtle: palette.stone40,
    divider: palette.stone30,
    overlay: "rgba(0,0,0,0.3)",
    overlaySoft: "rgba(0,0,0,0.28)",
    danger: palette.red500,
    warning: palette.amber500,
    onAccent: palette.white,
    onAccentMuted: "rgba(255,255,255,0.8)",
    onDark: palette.white,
  },
} as const;

export const colors = {
  primary: semanticColors.light.accent,
  primaryDark: semanticColors.light.accentStrong,
  primarySoft: semanticColors.light.accentSubtle,
  primaryBorder: semanticColors.light.accentBorder,
  foreground: semanticColors.light.textPrimary,
  body: semanticColors.light.textSecondary,
  muted: semanticColors.light.textTertiary,
  subtle: semanticColors.light.textMuted,
  disabled: semanticColors.light.textDisabled,
  iconMuted: semanticColors.light.iconMuted,
  hairline: semanticColors.light.borderMuted,
  border: semanticColors.light.border,
  borderSubtle: semanticColors.light.borderSubtle,
  divider: semanticColors.light.divider,
  background: semanticColors.light.page,
  backgroundMuted: semanticColors.light.pageMuted,
  surface: semanticColors.light.surface,
  surfacePressed: semanticColors.light.surfacePressed,
  surfaceMuted: semanticColors.light.surfaceMuted,
  surfaceRaised: semanticColors.light.surfaceRaised,
  chip: semanticColors.light.chip,
  overlay: semanticColors.light.overlay,
  overlaySoft: semanticColors.light.overlaySoft,
  danger: semanticColors.light.danger,
  warning: semanticColors.light.warning,
  white: semanticColors.light.onAccent,
  onPrimaryMuted: semanticColors.light.onAccentMuted,
  black: palette.black,
  googleBlue: palette.googleBlue,
} as const;

export const radius = {
  xs: 2,
  sm: 8,
  chip: 10,
  md: 12,
  lg: 16,
  xl: 20,
  full: 999,
} as const;

export const spacing = {
  none: 0,
  xxs: 2,
  xs: 3,
  sm: 4,
  md: 6,
  lg: 8,
  xl: 10,
  "2xl": 12,
  "3xl": 14,
  "4xl": 16,
  "5xl": 20,
  "6xl": 24,
  "7xl": 28,
  "8xl": 32,
  "9xl": 36,
  "10xl": 40,
  "12xl": 48,
} as const;

export const borderWidth = {
  hairline: 0.5,
  thin: 1,
  medium: 1.5,
  thick: 2,
} as const;
